# Generated by Django 5.1.6 on 2025-04-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0002_initial'),
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='study_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study_plans.studytask'),
        ),
    ]
