# Generated by Django 5.0 on 2025-04-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='subject',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
