# Generated by Django 5.0 on 2025-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='subject',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='max_members',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='specific_room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
