# Generated by Django 5.1.6 on 2025-04-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_tools', '0001_initial'),
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudysession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='study_groups.subject'),
        ),
    ]
